In [2]:
import numpy as np
import pandas as pd
import csv
import math

In [3]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [47]:
#read in files from train.csv and turn it into a numpy array
df = pd.read_csv('train.csv')
df = df.fillna(0)
df = df.to_numpy()
df

array([[1, 0, 3, ..., 7.25, 0, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, 0, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, 0, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, 0, 'Q']], dtype=object)

In [48]:
#correct contains values 0,1 representing the ground truth to whether the person survived or not
correct = df[:,1]
for i in range(len(correct)):
    if(correct[i]==0):
        correct[i]=-1

In [49]:
#deleting the column number, survival, name, ticket, cabin,  columns from array
df = np.delete(df,0,1)
df = np.delete(df,0,1)
df = np.delete(df,1,1)
df = np.delete(df,5,1)
df = np.delete(df,6,1)

In [7]:
df[1]

array([1, 'female', 38.0, 1, 0, 71.2833, 'C'], dtype=object)

In [50]:
#change string inputs to numbers
#specificaly male/female and cabinets
for x in df:
    if(x[1]=='male'):
        x[1]=1
    elif(x[1]=='female'):
        x[1]=2
    if(x[6]=='S'):
        x[6]=1
    elif(x[6]=='C'):
        x[6]=2
    elif(x[6]=='Q'):
        x[6]=3
df = df.astype('float64')

In [46]:
df[1]

array([ 3.,  2., 47.,  1.,  0.,  7.,  1.])

In [18]:
#feed forward values and get the output value for each test case
#output is a 891x1 vector that has the values that are squishified to be between 0,1 by sigmoid
def feedforward(df,theta):
    output = np.matmul(df,theta1)
    predictions = np.zeros(df.shape[0])
    for i in range(len(output)):
        if(output[i]>=0):
            predictions[i]=1
        if(output[i]<0):
            predictions[i]=-1
    return predictions

In [19]:
def update_theta(df,theta,correct):
    predictions = feedforward(df,theta)
    for i in range(len(df)):
        if(predictions[i]!=correct[i]):
            theta = theta + np.multiply(df[i],correct[i])
    return theta

In [51]:
theta1 = np.zeros(df.shape[1])
maxnumcorrect = 0
for x in range(10000):
    count = 0
    theta1 = update_theta(df,theta1,correct)
    predictions = feedforward(df,theta1)
    for x in range(df.shape[0]):
        if(predictions[x]==correct[x]):
            count+=1
    if(count>maxnumcorrect):
        maxnumcorrect = count

In [52]:
print(theta1)
predictions = feedforward(df,theta1)
print(maxnumcorrect)


[-114588.          249887.           -3036.29        -67141.
  -23595.            2849.31430001  -22467.        ]
708


In [54]:
testdata = pd.read_csv('test.csv')
testdata = testdata.fillna(0)
testdata = testdata.to_numpy()

In [55]:
testdata = np.delete(testdata,0,1)
testdata = np.delete(testdata,1,1)
testdata = np.delete(testdata,5,1)
testdata = np.delete(testdata,6,1)

In [57]:
#change string inputs to numbers
#specificaly male/female and cabinets
for x in testdata:
    if(x[1]=='male'):
        x[1]=1
    elif(x[1]=='female'):
        x[1]=2
    if(x[6]=='S'):
        x[6]=1
    elif(x[6]=='C'):
        x[6]=2
    elif(x[6]=='Q'):
        x[6]=3
testdata = testdata.astype('float64')

In [88]:
predictions = feedforward(testdata,theta1)
predictions = predictions.astype("int32")
output = np.zeros((testdata.shape[0]+1,2))
output = output.astype("str")
output[0,0] = "PassengerId"
output[0,1] = "Survived"
count = 0
for i in range(len(predictions)):
    if(predictions[i]==-1):
        predictions[i]=0
    output[i+1,0] = i+892
    output[i+1,1] = predictions[i]
    count+=1
print(count)
    
pd.DataFrame(output).to_csv('output.csv',header=None,index=None)

0
